import os
import yaml
import difflib
from pprint import pp as print
from langchain_community.agent_toolkits import JsonToolkit, create_json_agent
from langchain_community.tools.json.tool import JsonSpec
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
from prompts import prefix, suffix, sys, system_message
from langchain_openai import AzureChatOpenAI
from functions import llm, API_KEY
import logging

logging.basicConfig(
    level=logging.INFO,  # Change this to DEBUG for more detailed logging
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler()
    ]
)



model = AzureChatOpenAI(
    azure_endpoint="https://firstsenseai.openai.azure.com",
    azure_deployment="gpt432k",
    api_version="2024-05-01-preview",
    api_key=API_KEY,
    temperature=0,
    max_tokens=None,
)


@tool
def create_agent(file_path: str, query: str) -> str:
    """
    Create an agent to extract relevant information from a specified document.
    This function initializes an agent with the document located at the given
    file path and processes the query to extract information related
    to it. The agent will analyze the content of the document to identify
    relevant responses based on the query.

    Args:
        file_path (str): The path to the document file that the agent will analyze.
        query (str): The query to be processed by the agent.

    Returns:
        str: The response generated by the agent based on the provided query.
             This may include relevant information or references from the document.
    """
    logging.info("###CREATE AGENT TOOL###")
    logging.info(f"File Name: {file_path}, Claim: {query}")

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = yaml.load(f, Loader=yaml.FullLoader)
            logging.debug(f"Loaded data from {file_path}")
    except Exception as e:
        logging.error(f"Error reading the file {file_path}: {e}")
        return "Error in Create Agent"

    try:
        json_spec = JsonSpec(dict_=data, max_value_length=4000)
        json_toolkit = JsonToolkit(spec=json_spec)

        json_agent_executor = create_json_agent(
            handle_parsing_errors=True,
            prefix=prefix,
            suffix=suffix,
            llm=model,
            toolkit=json_toolkit,
            verbose=True,
        )
    except Exception as e:
        logging.error(f"Error during Create agent: {e}")
        return "Error in Create Agent"

    try: 
        response = json_agent_executor.invoke("Please analyze the following information and provide the relevant details you can extract:\n"
            + f"```{query}```"
            + "\n\nNote: Return the Final Answer in a readable format without modifying any information."
        )
        logging.info(f"Create Agent Successfull")

        return response
    except Exception as e:
        logging.error(f"Error invoking the Create agent for query {query}: {e}")
        return "Error in Create Agent"


@tool
def get_file_path(query: str) -> str:
    """
    Use this function when "Refer to the..." in the Answer."

    Args:
        query (str): Answer that contains a reference to a document.

    Returns:
        str: The file path of the document being referenced.
    """
    logging.info(f"###GET FILE NAME TOOL###")
    directory_path = "json-files"
    json_files = [
        file
        for root, dirs, files in os.walk(directory_path)
        for file in files
        if file.endswith((".json"))
    ]

    normalized_text = query.lower()

    file_path = difflib.get_close_matches(normalized_text, json_files, n=1, cutoff=0.0)

    if file_path:
        logging.info(f"Closest matching file for '{query}' is {file_path[0]}")
        return f"json-files/{file_path[0]}"
    else:
        logging.warning(f"No matching file found for query: {query}")
        return "Error in Get File Path"


messages = []


@tool
def guide(query: str) -> str:
    """
    Always use this tool before returning the Final Answer.

    Args:
        query (str): A string containing the input or query about the claim.

    Returns:
        str: An instruction for the next tool usage.
    """
    logging.info("###Guide Tool###")
    messages.append(("human", query))
    try:
        ai_message = llm.invoke(messages).content
        messages.append(("ai", ai_message))
        return ai_message
    except Exception as e:
        logging.error(f"Error Guide tool with '{query}': {e}")
        return "Error in Guide Tool"


tools = [guide, create_agent, get_file_path]

langgraph_agent_executor = create_react_agent(model, tools, state_modifier=system_message)
